# Generated by Django 4.2.6 on 2023-10-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_home_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
