# Generated by Django 4.2.6 on 2023-10-26 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_home_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='name',
        ),
    ]
