# Generated by Django 4.2.6 on 2023-11-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('mid_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('yourwork', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='Home/')),
                ('telegram', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
