# Generated by Django 4.2.6 on 2023-11-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_remove_about_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='based_in',
            field=models.CharField(default='Birjand - Iran', max_length=50),
        ),
        migrations.AddField(
            model_name='about',
            name='your_job',
            field=models.CharField(default='Mechanical engineering', max_length=50),
        ),
        migrations.AlterField(
            model_name='about',
            name='photo',
            field=models.ImageField(upload_to='About/'),
        ),
    ]
