# Generated by Django 4.2.6 on 2023-11-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_about_based_in_about_your_job_alter_about_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='summery_about',
            field=models.TextField(default='salam'),
        ),
    ]
