# Generated by Django 4.2.6 on 2023-11-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_about_summery_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_service', models.CharField(max_length=50)),
                ('about_your_service', models.TextField()),
                ('photo', models.ImageField(upload_to='About/service/')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_skill', models.CharField(max_length=50)),
                ('percent', models.IntegerField()),
            ],
        ),
    ]
