# Generated by Django 4.2.6 on 2023-12-26 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_works'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Works',
        ),
    ]
